In [ ]:
# Bài 1

import numpy as np

arr1 = np.arange(1, 11)
print("arr1:", arr1)

shape1 = arr1.shape
dtype1 = arr1.dtype
print("shape1:", shape1)
print("dtype1:", dtype1)

arr1_float = arr1.astype(np.float32)
print("arr1_float:", arr1_float)
print("dtype_float:", arr1_float.dtype)

arr2 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print("arr2:\n", arr2)

shape2 = arr2.shape
dtype2 = arr2.dtype
print("shape2:", shape2)
print("dtype2:", dtype2)


arr1: [ 1  2  3  4  5  6  7  8  9 10]
shape1: (10,)
dtype1: int64
arr1_float: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
dtype_float: float32
arr2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
shape2: (3, 3)
dtype2: int64


In [5]:
# Bài 2

import numpy as np

arr1 = np.arange(1, 11)

# Indexing
first_elem = arr1[0]      
last_elem = arr1[-1]      
middle_elem = arr1[5]    

sliced_arr = arr1[2:6]

arr2 = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])

row2 = arr2[1]

col3 = arr2[:, 2]

print("arr1 =", arr1)
print("arr2 =\n", arr2)

print("first_elem =", first_elem)
print("last_elem =", last_elem)
print("middle_elem =", middle_elem)

print("sliced_arr =", sliced_arr)
print("row2 =", row2)
print("col3 =", col3)


arr1 = [ 1  2  3  4  5  6  7  8  9 10]
arr2 =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
first_elem = 1
last_elem = 10
middle_elem = 6
sliced_arr = [3 4 5 6]
row2 = [4 5 6]
col3 = [3 6 9]


In [6]:
# Bài 3

import numpy as np

arr = np.array([[88, 35, 62], [11, 98, 34],[64, 24, 48]])

min_val = np.min(arr)
max_val = np.max(arr)
sum_val = np.sum(arr)
mean_val = np.mean(arr)
std_val = np.std(arr)

sum_col = np.sum(arr, axis=0)
mean_col = np.mean(arr, axis=0)

sum_row = np.sum(arr, axis=1)
mean_row = np.mean(arr, axis=1)

print("Min:", min_val)
print("Max:", max_val)
print("Sum:", sum_val)
print("Mean:", mean_val)
print("STD:", std_val)

print("\nSumOfColumn:", sum_col)
print("MeanOfColumn:", mean_col)

print("\nSumOfRow:", sum_row)
print("MeanOfRow:", mean_row)


Min: 11
Max: 98
Sum: 464
Mean: 51.55555555555556
STD: 27.38252123409754

SumOfColumn: [163 157 144]
MeanOfColumn: [54.33333333 52.33333333 48.        ]

SumOfRow: [185 143 136]
MeanOfRow: [61.66666667 47.66666667 45.33333333]


In [7]:
# Bài 4

import numpy as np

A = np.array([
    [5, 6, 8],
    [7, 2, 4],
    [1, 6, 3]
])

B = np.array([10, 20, 30])

add_result = A + B

sub_result = A - B

print("Kết quả phép cộng A + B:\n")
print(add_result)

print("\nKết quả phép trừ A - B:\n")
print(sub_result)


Kết quả phép cộng A + B:

[[15 26 38]
 [17 22 34]
 [11 26 33]]

Kết quả phép trừ A - B:

[[ -5 -14 -22]
 [ -3 -18 -26]
 [ -9 -14 -27]]


In [8]:
# Bài 5

import numpy as np
import time

arr = np.random.randint(1, 21, size=10)
print("Mảng ban đầu:", arr)

square = arr ** 2
sqrt_arr = np.sqrt(arr)

print("\nBình phương (vectorized):", square)
print("Căn bậc hai (vectorized):", sqrt_arr)

add_result = np.add(arr, 5)        
mul_result = np.multiply(arr, 2)   
sqrt_result = np.sqrt(arr)         

print("\nKết quả dùng np.add(arr, 5):", add_result)
print("Kết quả dùng np.multiply(arr, 2):", mul_result)
print("Kết quả dùng np.sqrt(arr):", sqrt_result)

arr2d = np.random.randint(1, 21, size=(1000, 1000))

start_vec = time.time()
vec_result = arr2d * 2
end_vec = time.time()

start_loop = time.time()
loop_result = np.zeros_like(arr2d)

for i in range(arr2d.shape[0]):
    for j in range(arr2d.shape[1]):
        loop_result[i, j] = arr2d[i, j] * 2

end_loop = time.time()

print("\n⏱ Thời gian vectorization :", end_vec - start_vec)
print("⏱ Thời gian vòng lặp thủ công:", end_loop - start_loop)


Mảng ban đầu: [12 10  9  3  4 14 10  2 16 13]

Bình phương (vectorized): [144 100  81   9  16 196 100   4 256 169]
Căn bậc hai (vectorized): [3.46410162 3.16227766 3.         1.73205081 2.         3.74165739
 3.16227766 1.41421356 4.         3.60555128]

Kết quả dùng np.add(arr, 5): [17 15 14  8  9 19 15  7 21 18]
Kết quả dùng np.multiply(arr, 2): [24 20 18  6  8 28 20  4 32 26]
Kết quả dùng np.sqrt(arr): [3.46410162 3.16227766 3.         1.73205081 2.         3.74165739
 3.16227766 1.41421356 4.         3.60555128]

⏱ Thời gian vectorization : 0.0013201236724853516
⏱ Thời gian vòng lặp thủ công: 0.18435287475585938


In [9]:
# Bài 6

import numpy as np

arr = np.array([[3, 7, 4, 5], [3, 5, 2, 4],[6, 3, 9, 7], [4, 8, 3, 5]])

sum_col = np.sum(arr, axis=0)
mean_col = np.mean(arr, axis=0)
std_col = np.std(arr, axis=0)

sum_row = np.sum(arr, axis=1)
mean_row = np.mean(arr, axis=1)
std_row = np.std(arr, axis=1)

print("Tổng theo cột (axis=0):", sum_col)
print("Trung bình theo cột (axis=0):", mean_col)
print("Độ lệch chuẩn theo cột (axis=0):", std_col)

print("\nTổng theo hàng (axis=1):", sum_row)
print("Trung bình theo hàng (axis=1):", mean_row)
print("Độ lệch chuẩn theo hàng (axis=1):", std_row)


Tổng theo cột (axis=0): [16 23 18 21]
Trung bình theo cột (axis=0): [4.   5.75 4.5  5.25]
Độ lệch chuẩn theo cột (axis=0): [1.22474487 1.92028644 2.6925824  1.08972474]

Tổng theo hàng (axis=1): [19 14 25 20]
Trung bình theo hàng (axis=1): [4.75 3.5  6.25 5.  ]
Độ lệch chuẩn theo hàng (axis=1): [1.47901995 1.11803399 2.16506351 1.87082869]


In [10]:
# Bài 7

import numpy as np
import time

A = np.array([
    [8, 12, 14, 6, 4],
    [18, 13, 2, 2, 12],
    [6, 18, 5, 10, 10],
    [9, 2, 4, 12, 12],
    [2, 3, 2, 17, 3]
])

b = np.array([10, 20, 30, 40, 50])

add_result = A + b
sub_result = A - b

print("Kết quả cộng (broadcasting):\n", add_result, "\n")
print("Kết quả trừ (broadcasting):\n", sub_result, "\n")

sqrt_result = np.sqrt(A)
add5_result = np.add(A, 5)

print("Kết quả căn bậc hai (ufunc):\n", sqrt_result, "\n")
print("Kết quả cộng 5 vào mảng (ufunc):\n", add5_result, "\n")

start = time.time()
manual = np.zeros_like(A)

for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        manual[i, j] = A[i, j] + 5

end = time.time()
print("Thời gian thực thi vòng lặp thủ công:", round(end - start, 6), "giây")


Kết quả cộng (broadcasting):
 [[18 32 44 46 54]
 [28 33 32 42 62]
 [16 38 35 50 60]
 [19 22 34 52 62]
 [12 23 32 57 53]] 

Kết quả trừ (broadcasting):
 [[ -2  -8 -16 -34 -46]
 [  8  -7 -28 -38 -38]
 [ -4  -2 -25 -30 -40]
 [ -1 -18 -26 -28 -38]
 [ -8 -17 -28 -23 -47]] 

Kết quả căn bậc hai (ufunc):
 [[2.82842712 3.46410162 3.74165739 2.44948974 2.        ]
 [4.24264069 3.60555128 1.41421356 1.41421356 3.46410162]
 [2.44948974 4.24264069 2.23606798 3.16227766 3.16227766]
 [3.         1.41421356 2.         3.46410162 3.46410162]
 [1.41421356 1.73205081 1.41421356 4.12310563 1.73205081]] 

Kết quả cộng 5 vào mảng (ufunc):
 [[13 17 19 11  9]
 [23 18  7  7 17]
 [11 23 10 15 15]
 [14  7  9 17 17]
 [ 7  8  7 22  8]] 

Thời gian thực thi vòng lặp thủ công: 0.000128 giây


In [11]:
# Bài 8

import numpy as np

A = np.array([
    [6, 9, 7],
    [2, 1, 5],
    [7, 8, 3]
])
A_inv = np.linalg.inv(A)
print("Ma trận nghịch đảo:\n", A_inv, "\n")
eig_vals, eig_vecs = np.linalg.eig(A)

print("Giá trị riêng của ma trận:", eig_vals, "\n")
print("Véc tơ riêng của ma trận:\n", eig_vecs)


Ma trận nghịch đảo:
 [[-0.3627451   0.28431373  0.37254902]
 [ 0.28431373 -0.30392157 -0.15686275]
 [ 0.08823529  0.14705882 -0.11764706]] 

Giá trị riêng của ma trận: [15.56193425 -1.69500073 -3.86693352] 

Véc tơ riêng của ma trận:
 [[-0.73366783 -0.72778239  0.22947148]
 [-0.30862775  0.68155654 -0.7417394 ]
 [-0.60537626 -0.07624612  0.63021068]]
