In [1]:
# Bài 1

lst = [1, 2, 3, 2, 5, 1, 7, 9, 9, 4]

even_positions = lst[0::2]

tpl = tuple(lst)

d = {i: lst[i] for i in range(len(lst))}

s = set(lst)
removed = len(lst) - len(s)

print("Các vị trí chẵn:", even_positions)
print("Tuple:", tpl)
print("Dict:", d)
print("Set:", s)
print("Số phần tử bị loại trùng:", removed)


Các vị trí chẵn: [1, 3, 5, 7, 9]
Tuple: (1, 2, 3, 2, 5, 1, 7, 9, 9, 4)
Dict: {0: 1, 1: 2, 2: 3, 3: 2, 4: 5, 5: 1, 6: 7, 7: 9, 8: 9, 9: 4}
Set: {1, 2, 3, 4, 5, 7, 9}
Số phần tử bị loại trùng: 3


In [3]:
# Bài 2

import json

with open('data.txt', 'r', encoding="utf-8") as f:
    for i, line in enumerate(f):
        print(line.strip())

students = {
    "name": "Gia Bao",
    "age": 20,
    "courses": ["Python", "Django", "Machine Learning"]
}
with open('student.json', 'w', encoding="utf-8") as f:
    json.dump(students, f, ensure_ascii=False, indent=4)
    
with open('student.json', 'r', encoding="utf-8") as f:
    data = json.load(f)
    print(data)
    

dòng 1
dong 2
dong 3
dòng 4
dòng 5
{'name': 'Gia Bao', 'age': 20, 'courses': ['Python', 'Django', 'Machine Learning']}


In [6]:
# Bài 3

import numpy as np

arr = np.arange(12).reshape(3, 4)
print(arr)

row2 = arr[1]
col3 = arr[:, 2]
sub = arr[0:2, 1:3]
arr_float = arr.astype(np.float64)

print("Hàng 2:", row2)
print("Cột 3:", col3)
print("Submatrix:", sub)
print("Dtype mới:", arr_float.dtype)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Hàng 2: [4 5 6 7]
Cột 3: [ 2  6 10]
Submatrix: [[1 2]
 [5 6]]
Dtype mới: float64


In [7]:
# Bài 4

import pandas as pd

score_series = pd.Series([7.5, 8.0, 6.5, 9.0, 8.5])
print(score_series)

name = ['An','Bình','Châu','Dũng','Hà']
age = [20,21,22,20,23]
score = [7.5, 8.0, 6.5, 9.0, 8.5]

df = pd.DataFrame({
    "name": name,
    "age": age,
    "score": score
})

df.info()
print(df.describe())

filtered = df.loc[df["score"] >= 8, :]
print("Sinh viên >= 8 điểm:")
print(filtered.values.tolist())


0    7.5
1    8.0
2    6.5
3    9.0
4    8.5
dtype: float64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   name    5 non-null      object 
 1   age     5 non-null      int64  
 2   score   5 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 252.0+ bytes
            age     score
count   5.00000  5.000000
mean   21.20000  7.900000
std     1.30384  0.961769
min    20.00000  6.500000
25%    20.00000  7.500000
50%    21.00000  8.000000
75%    22.00000  8.500000
max    23.00000  9.000000
Sinh viên >= 8 điểm:
[['Bình', 21, 8.0], ['Dũng', 20, 9.0], ['Hà', 23, 8.5]]


In [9]:
# Bài 5

import pandas as pd

df_students = pd.read_csv("students.csv", names=["id", "name"])
df_scores = pd.read_csv("scores.csv", names=["id", "score"])

df = pd.merge(df_students, df_scores, on="id")

report = df.groupby(["id", "name"])["score"].agg(
    score_min="min",
    score_max="max",
    score_mean="mean"
).reset_index()

print(report)

report.to_csv("report.csv", index=False)


   id  name  score_min  score_max  score_mean
0   1    An          8          8         8.0
1   2  Binh          9          9         9.0
2   3  Chau          7          7         7.0


In [10]:
# Bài 6

import numpy as np

a = np.array([[1], [2], [3], [4]])      
b = np.array([[10, 20, 30, 40, 50]])   

c = a * b
print("Kết quả a*b:\n", c)

sqrt_c = np.sqrt(c)
log_c = np.log(c)
print("sqrt =\n", sqrt_c)
print("log =\n", log_c)

mean_axis1 = c.mean(axis=1)
min_axis1 = c.min(axis=1)
max_axis1 = c.max(axis=1)
std_axis1 = c.std(axis=1)

print("mean theo axis=1 =", mean_axis1)
print("min theo axis=1 =", min_axis1)
print("max theo axis=1 =", max_axis1)
print("std theo axis=1 =", std_axis1)



Kết quả a*b:
 [[ 10  20  30  40  50]
 [ 20  40  60  80 100]
 [ 30  60  90 120 150]
 [ 40  80 120 160 200]]
sqrt =
 [[ 3.16227766  4.47213595  5.47722558  6.32455532  7.07106781]
 [ 4.47213595  6.32455532  7.74596669  8.94427191 10.        ]
 [ 5.47722558  7.74596669  9.48683298 10.95445115 12.24744871]
 [ 6.32455532  8.94427191 10.95445115 12.64911064 14.14213562]]
log =
 [[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
 [2.99573227 3.68887945 4.09434456 4.38202663 4.60517019]
 [3.40119738 4.09434456 4.49980967 4.78749174 5.01063529]
 [3.68887945 4.38202663 4.78749174 5.07517382 5.29831737]]
mean theo axis=1 = [ 30.  60.  90. 120.]
min theo axis=1 = [10 20 30 40]
max theo axis=1 = [ 50 100 150 200]
std theo axis=1 = [14.14213562 28.28427125 42.42640687 56.56854249]
